# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee8037a6e4502eca3387a17a848044c73123ca1886053a68d870ab0eee5f8b8e795055a9e322e4f7d7115a12efe2724c0faad13d5e02d1591d879d1c5bb401e4

test:
  secret_key_base: 73dc37fdbd03ea243731fa1904531364c6692e3c575cfca5d70db8775a8149c0fa80ae6fa0abc351d30e646fb5c197ccd9c07de9062e89ebf990993b34a10e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
